name: Test CD Workflow

on:
    push:
    workflow_dispatch:

jobs:
    run_tests:
        name: Testing stage
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Start containers
              run: docker compose -f "compose.test.yaml" up --build -d

            - name: Wait containers
              run: sleep 5

            - name: Run tests
              run: docker exec -i api pytest
            
            - name: Clean up
              run: docker compose -f "compose.test.yaml" down --timeout 1